---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/stepcash/aurais/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -R .well-known $DEPLOYPATH 2>/dev/null || true